#' Estimate parameters from Real Datasets
#'
#' This is the core function of estimating parameters from real single-cell RNA
#' sequencing datasets via establishing Docker containers.
#'
#' @param ref_data A matrix for one dataset or a list of datasets with their own
#' names.
#' @param method A character or a string of methods. It can be `all` as all
#' methods are used to estimate paramters from real data.
#' @param other_prior A list with names of certain parameters. Some methods need
#' extra parameters to execute the estimation step, so you must input them.
#' @param seed A random seed. Default value is generated by `random_seed`.
#' @param verbose Logical. Whether to return messages or not.
#'
#' @return A list of estimated parameters and detection results
#' @importFrom tidyr crossing
#' @importFrom assertthat assert_that
#' @importFrom purrr map
#' @importFrom stats setNames
#' @export
#'
estimate_parameters_container <- function(
    ref_data,
    method,
    other_prior = list(),
    seed = random_seed(),
    verbose = TRUE
){
  # Check-----------------------------------------------------------------------
  if(is.matrix(ref_data)){
    ref_data <- list(refdata = ref_data)
  }
  assertthat::assert_that(is.list(ref_data))

  # Prepare methods-------------------------------------------------------------
  all_methods <- c("BASiCS",
                   "BEARscc",
                   "CancerInSilico",
                   "dropsim",
                   "dyngen",
                   "dyntoy",
                   "ESCO",
                   "hierarchicell",
                   "Kersplat",
                   "Lun",
                   "Lun2",
                   "MFA",
                   "muscat",
                   "phenopath",
                   "POWSC",
                   "powsimR",
                   "PROSSTT",
                   "scDD",
                   "scDesign",
                   "scDesign2",
                   "scGAN",
                   "SCRIP",
                   "Simple",
                   "SparseDC",
                   "SPARSim",
                   "Splat",
                   "SplatPop",
                   "SPsimSeq",
                   "SymSim",
                   "TedSim",
                   "VeloSim",
                   "zinbwave",
                   "zinbwaveZinger",
                   "zingeR")
  if(method[1] == "all"){
    method <- all_methods
  }
  assertthat::assert_that(all(method %in% all_methods))

  # Estimation design-----------------------------------------------------------
  design <- tidyr::crossing(dataset_id = names(ref_data),
                            method_id = method)
  # Run methods with each dataset-----------------------------------------------
  result <- purrr::map(
    .x = seq_len(nrow(design)),
    .f = function(er) {
      if(verbose){
        message(paste0("Learning parameters from data ", er))
      }
      seed <- ifelse(is.null(seed), random_seed(), seed)
      other_prior_exec <- check_prior_info(method = design$method_id[er],
                                           step = "estimation",
                                           other_prior = other_prior)
      method_execute_container_estimate(
        ref_data = ref_data[[design$dataset_id[er]]],
        method = design$method_id[er],
        other_prior = other_prior_exec,
        seed = seed,
        verbose = verbose
      )
    }
  )
  result_names <- paste0(design$dataset_id, "_", design$method_id)
  result <- stats::setNames(result, result_names) %>%
    add_class(define_class = "simpipe_estimation")
  return(result)
}
